// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.1 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/jarenzhang/qqvideo_common.jce'
// **********************************************************************

package com.tencent.qqlive.jcehelper.test;

public final class EONAViewType implements java.io.Serializable
{
    private static EONAViewType[] __values = new EONAViewType[34];
    private int __value;
    private String __T = new String();

    public static final int _EnumONAMultPoster = 0;
    public static final EONAViewType EnumONAMultPoster = new EONAViewType(0,_EnumONAMultPoster,"EnumONAMultPoster");
    public static final int _EnumONAGalleryPoster = 1;
    public static final EONAViewType EnumONAGalleryPoster = new EONAViewType(1,_EnumONAGalleryPoster,"EnumONAGalleryPoster");
    public static final int _EnumONAPosterTitle = 2;
    public static final EONAViewType EnumONAPosterTitle = new EONAViewType(2,_EnumONAPosterTitle,"EnumONAPosterTitle");
    public static final int _EnumONASplitLine = 3;
    public static final EONAViewType EnumONASplitLine = new EONAViewType(3,_EnumONASplitLine,"EnumONASplitLine");
    public static final int _EnumONAStarList = 4;
    public static final EONAViewType EnumONAStarList = new EONAViewType(4,_EnumONAStarList,"EnumONAStarList");
    public static final int _EnumONANewsItem = 5;
    public static final EONAViewType EnumONANewsItem = new EONAViewType(5,_EnumONANewsItem,"EnumONANewsItem");
    public static final int _EnumONAMatchSchedule = 6;
    public static final EONAViewType EnumONAMatchSchedule = new EONAViewType(6,_EnumONAMatchSchedule,"EnumONAMatchSchedule");
    public static final int _EnumONAGrid = 7;
    public static final EONAViewType EnumONAGrid = new EONAViewType(7,_EnumONAGrid,"EnumONAGrid");
    public static final int _EnumONADetailsVideoCircleShare = 8;
    public static final EONAViewType EnumONADetailsVideoCircleShare = new EONAViewType(8,_EnumONADetailsVideoCircleShare,"EnumONADetailsVideoCircleShare");
    public static final int _EnumONADetailsToolbar = 9;
    public static final EONAViewType EnumONADetailsToolbar = new EONAViewType(9,_EnumONADetailsToolbar,"EnumONADetailsToolbar");
    public static final int _EnumONADetailsVideoList = 10;
    public static final EONAViewType EnumONADetailsVideoList = new EONAViewType(10,_EnumONADetailsVideoList,"EnumONADetailsVideoList");
    public static final int _EnumONADetailsPosterList = 11;
    public static final EONAViewType EnumONADetailsPosterList = new EONAViewType(11,_EnumONADetailsPosterList,"EnumONADetailsPosterList");
    public static final int _EnumONADetailsIntroduction = 12;
    public static final EONAViewType EnumONADetailsIntroduction = new EONAViewType(12,_EnumONADetailsIntroduction,"EnumONADetailsIntroduction");
    public static final int _EnumONACommentWrite = 13;
    public static final EONAViewType EnumONACommentWrite = new EONAViewType(13,_EnumONACommentWrite,"EnumONACommentWrite");
    public static final int _EnumONAHeadPoster = 14;
    public static final EONAViewType EnumONAHeadPoster = new EONAViewType(14,_EnumONAHeadPoster,"EnumONAHeadPoster");
    public static final int _EnumONASearchPoster = 15;
    public static final EONAViewType EnumONASearchPoster = new EONAViewType(15,_EnumONASearchPoster,"EnumONASearchPoster");
    public static final int _EnumONANoSearchHit = 16;
    public static final EONAViewType EnumONANoSearchHit = new EONAViewType(16,_EnumONANoSearchHit,"EnumONANoSearchHit");
    public static final int _EnumONABulletinBoard = 17;
    public static final EONAViewType EnumONABulletinBoard = new EONAViewType(17,_EnumONABulletinBoard,"EnumONABulletinBoard");
    public static final int _EnumONAAppInfo = 18;
    public static final EONAViewType EnumONAAppInfo = new EONAViewType(18,_EnumONAAppInfo,"EnumONAAppInfo");
    public static final int _EnumONAStarIntroduction = 19;
    public static final EONAViewType EnumONAStarIntroduction = new EONAViewType(19,_EnumONAStarIntroduction,"EnumONAStarIntroduction");
    public static final int _EnumONAStarNews = 20;
    public static final EONAViewType EnumONAStarNews = new EONAViewType(20,_EnumONAStarNews,"EnumONAStarNews");
    public static final int _EnumONAQuoteComment = 21;
    public static final EONAViewType EnumONAQuoteComment = new EONAViewType(21,_EnumONAQuoteComment,"EnumONAQuoteComment");
    public static final int _EnumONASummary = 22;
    public static final EONAViewType EnumONASummary = new EONAViewType(22,_EnumONASummary,"EnumONASummary");
    public static final int _EnumONAActorList = 23;
    public static final EONAViewType EnumONAActorList = new EONAViewType(23,_EnumONAActorList,"EnumONAActorList");
    public static final int _EnumONAPictureWall = 24;
    public static final EONAViewType EnumONAPictureWall = new EONAViewType(24,_EnumONAPictureWall,"EnumONAPictureWall");
    public static final int _EnumONAPursuit = 25;
    public static final EONAViewType EnumONAPursuit = new EONAViewType(25,_EnumONAPursuit,"EnumONAPursuit");
    public static final int _EnumONALiveTrailerCountdown = 26;
    public static final EONAViewType EnumONALiveTrailerCountdown = new EONAViewType(26,_EnumONALiveTrailerCountdown,"EnumONALiveTrailerCountdown");
    public static final int _EnumONALiveAttent = 27;
    public static final EONAViewType EnumONALiveAttent = new EONAViewType(27,_EnumONALiveAttent,"EnumONALiveAttent");
    public static final int _EnumONALivePayTicketInfo = 28;
    public static final EONAViewType EnumONALivePayTicketInfo = new EONAViewType(28,_EnumONALivePayTicketInfo,"EnumONALivePayTicketInfo");
    public static final int _EnumONALiveVIPRights = 29;
    public static final EONAViewType EnumONALiveVIPRights = new EONAViewType(29,_EnumONALiveVIPRights,"EnumONALiveVIPRights");
    public static final int _EnumONALiveIntroduction = 30;
    public static final EONAViewType EnumONALiveIntroduction = new EONAViewType(30,_EnumONALiveIntroduction,"EnumONALiveIntroduction");
    public static final int _EnumONAVoteRank = 31;
    public static final EONAViewType EnumONAVoteRank = new EONAViewType(31,_EnumONAVoteRank,"EnumONAVoteRank");
    public static final int _EnumONAActorRank = 32;
    public static final EONAViewType EnumONAActorRank = new EONAViewType(32,_EnumONAActorRank,"EnumONAActorRank");
    public static final int _EnumONACompeteSchedule = 33;
    public static final EONAViewType EnumONACompeteSchedule = new EONAViewType(33,_EnumONACompeteSchedule,"EnumONACompeteSchedule");

    public static EONAViewType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static EONAViewType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private EONAViewType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
